name = input("Enter name: ")
age = input("Enter age: ")
course = input("Enter course: ")
college = input("Enter college: ")
email = input("Enter email: ")

print("╔════════════════════════════════╗")
print("║        STUDENT BIO CARD        ║")
print("╠════════════════════════════════╣")
print("║ Name    :", name, "            ║")
print("║ Age     :", age, "years        ║")
print("║ Course  :", course, "          ║")
print("║ College :", college, "         ║")
print("║ Email   :", email, "           ║")    
print("╚════════════════════════════════╝")